# Generated by Django 3.2 on 2025-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250522_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
    ]
